version: '3.8'

services:
  frontend:
    build: 
      context: ../frontend/
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/workspace:cached
      - ../spec:/spec:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the backend container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:backend

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  backend:
    build: 
      context: ../backend/
      dockerfile: Dockerfile
    volumes:
      - ../backend:/workspace:cached
      - ../spec:/spec:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment to change startup options
    # environment: {}
    
    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)